<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ContentBlock;

/**
 * ContentBlockSeeder
 * 
 * Seed 168 content blocks mặc định cho toàn bộ website.
 * Được tổ chức theo 9 groups để dễ quản lý trong admin UI.
 */
class ContentBlockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $blocks = [
            // ============================================
            // GROUP 1: HOME HERO (9 blocks) - 3 slides
            // ============================================
            [
                'key' => 'hero_slide_1_title',
                'value' => 'HOA TƯƠI CAO CẤP',
                'type' => 'text',
                'group' => 'home_hero',
                'label' => 'Slide 1 - Tiêu đề',
                'description' => 'Tiêu đề chính của slide đầu tiên',
                'order' => 1,
            ],
            [
                'key' => 'hero_slide_1_description',
                'value' => 'Mang đến không gian sống tươi mới',
                'type' => 'textarea',
                'group' => 'home_hero',
                'label' => 'Slide 1 - Mô tả',
                'description' => 'Mô tả ngắn cho slide 1',
                'order' => 2,
            ],
            [
                'key' => 'hero_slide_1_cta',
                'value' => 'Khám phá ngay',
                'type' => 'text',
                'group' => 'home_hero',
                'label' => 'Slide 1 - Nút CTA',
                'description' => 'Text nút call-to-action slide 1',
                'order' => 3,
            ],
            [
                'key' => 'hero_slide_2_title',
                'value' => 'BÓ HOA TẶNG YÊU THƯƠNG',
                'type' => 'text',
                'group' => 'home_hero',
                'label' => 'Slide 2 - Tiêu đề',
                'description' => 'Tiêu đề chính của slide thứ hai',
                'order' => 4,
            ],
            [
                'key' => 'hero_slide_2_description',
                'value' => 'Gửi trọn tình cảm đến người thân yêu',
                'type' => 'textarea',
                'group' => 'home_hero',
                'label' => 'Slide 2 - Mô tả',
                'description' => 'Mô tả ngắn cho slide 2',
                'order' => 5,
            ],
            [
                'key' => 'hero_slide_2_cta',
                'value' => 'Xem bộ sưu tập',
                'type' => 'text',
                'group' => 'home_hero',
                'label' => 'Slide 2 - Nút CTA',
                'description' => 'Text nút call-to-action slide 2',
                'order' => 6,
            ],
            [
                'key' => 'hero_slide_3_title',
                'value' => 'THIẾT KẾ THEO YÊU CẦU',
                'type' => 'text',
                'group' => 'home_hero',
                'label' => 'Slide 3 - Tiêu đề',
                'description' => 'Tiêu đề chính của slide thứ ba',
                'order' => 7,
            ],
            [
                'key' => 'hero_slide_3_description',
                'value' => 'Tạo nên bó hoa độc đáo theo phong cách riêng',
                'type' => 'textarea',
                'group' => 'home_hero',
                'label' => 'Slide 3 - Mô tả',
                'description' => 'Mô tả ngắn cho slide 3',
                'order' => 8,
            ],
            [
                'key' => 'hero_slide_3_cta',
                'value' => 'Liên hệ ngay',
                'type' => 'text',
                'group' => 'home_hero',
                'label' => 'Slide 3 - Nút CTA',
                'description' => 'Text nút call-to-action slide 3',
                'order' => 9,
            ],

            // ============================================
            // GROUP 2: HOME SECTIONS (15 blocks)
            // ============================================
            [
                'key' => 'home_categories_title',
                'value' => 'Danh Mục Sản Phẩm',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Categories - Tiêu đề',
                'description' => 'Tiêu đề section danh mục',
                'order' => 1,
            ],
            [
                'key' => 'home_categories_subtitle',
                'value' => 'Khám phá bộ sưu tập hoa tươi đa dạng',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Categories - Mô tả ngắn',
                'description' => 'Mô tả section danh mục',
                'order' => 2,
            ],
            [
                'key' => 'home_products_title',
                'value' => 'Sản Phẩm Nổi Bật',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Products - Tiêu đề',
                'description' => 'Tiêu đề section sản phẩm nổi bật',
                'order' => 3,
            ],
            [
                'key' => 'home_products_subtitle',
                'value' => 'Những bó hoa được yêu thích nhất',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Products - Mô tả ngắn',
                'description' => 'Mô tả section sản phẩm',
                'order' => 4,
            ],
            [
                'key' => 'home_products_view_all',
                'value' => 'Xem tất cả',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Products - Nút xem tất cả',
                'description' => 'Text nút xem tất cả sản phẩm',
                'order' => 5,
            ],
            [
                'key' => 'home_brand_values_title',
                'value' => 'Tại Sao Chọn Chúng Tôi',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Brand Values - Tiêu đề',
                'description' => 'Tiêu đề section giá trị thương hiệu',
                'order' => 6,
            ],
            [
                'key' => 'home_brand_value_1_title',
                'value' => 'Hoa Tươi 100%',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Giá trị 1 - Tiêu đề',
                'description' => 'Tiêu đề giá trị thứ nhất',
                'order' => 7,
            ],
            [
                'key' => 'home_brand_value_1_description',
                'value' => 'Cam kết hoa tươi mới mỗi ngày',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Giá trị 1 - Mô tả',
                'description' => 'Mô tả giá trị thứ nhất',
                'order' => 8,
            ],
            [
                'key' => 'home_brand_value_2_title',
                'value' => 'Giao Hàng Nhanh',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Giá trị 2 - Tiêu đề',
                'description' => 'Tiêu đề giá trị thứ hai',
                'order' => 9,
            ],
            [
                'key' => 'home_brand_value_2_description',
                'value' => 'Giao hàng trong 2 giờ nội thành',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Giá trị 2 - Mô tả',
                'description' => 'Mô tả giá trị thứ hai',
                'order' => 10,
            ],
            [
                'key' => 'home_brand_value_3_title',
                'value' => 'Thiết Kế Đẹp',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Giá trị 3 - Tiêu đề',
                'description' => 'Tiêu đề giá trị thứ ba',
                'order' => 11,
            ],
            [
                'key' => 'home_brand_value_3_description',
                'value' => 'Thiết kế tinh tế bởi florist chuyên nghiệp',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Giá trị 3 - Mô tả',
                'description' => 'Mô tả giá trị thứ ba',
                'order' => 12,
            ],
            [
                'key' => 'home_inspiration_title',
                'value' => 'Cảm Hứng Hoa Tươi',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Inspiration - Tiêu đề',
                'description' => 'Tiêu đề section cảm hứng',
                'order' => 13,
            ],
            [
                'key' => 'home_inspiration_subtitle',
                'value' => 'Khám phá xu hướng trang trí hoa mới nhất',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Inspiration - Mô tả ngắn',
                'description' => 'Mô tả section cảm hứng',
                'order' => 14,
            ],
            [
                'key' => 'home_instagram_title',
                'value' => 'Theo Dõi Chúng Tôi',
                'type' => 'text',
                'group' => 'home_sections',
                'label' => 'Instagram - Tiêu đề',
                'description' => 'Tiêu đề section Instagram',
                'order' => 15,
            ],

            // =========================================
            // GROUP 3: PRODUCT PAGES (30 blocks)
            // =========================================
            [
                'key' => 'products_page_title',
                'value' => 'Tất Cả Sản Phẩm',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Trang sản phẩm - Tiêu đề',
                'description' => 'Tiêu đề trang danh sách sản phẩm',
                'order' => 1,
            ],
            [
                'key' => 'products_filter_category',
                'value' => 'Danh mục',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Filter - Danh mục',
                'description' => 'Label bộ lọc danh mục',
                'order' => 2,
            ],
            [
                'key' => 'products_filter_price',
                'value' => 'Khoảng giá',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Filter - Giá',
                'description' => 'Label bộ lọc giá',
                'order' => 3,
            ],
            [
                'key' => 'products_filter_color',
                'value' => 'Màu sắc',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Filter - Màu sắc',
                'description' => 'Label bộ lọc màu sắc',
                'order' => 4,
            ],
            [
                'key' => 'products_filter_occasion',
                'value' => 'Dịp tặng',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Filter - Dịp tặng',
                'description' => 'Label bộ lọc dịp tặng',
                'order' => 5,
            ],
            [
                'key' => 'products_sort_label',
                'value' => 'Sắp xếp theo',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Sort - Label',
                'description' => 'Label sắp xếp',
                'order' => 6,
            ],
            [
                'key' => 'products_sort_newest',
                'value' => 'Mới nhất',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Sort - Mới nhất',
                'description' => 'Tùy chọn sắp xếp mới nhất',
                'order' => 7,
            ],
            [
                'key' => 'products_sort_price_asc',
                'value' => 'Giá thấp đến cao',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Sort - Giá tăng dần',
                'description' => 'Tùy chọn sắp xếp giá tăng',
                'order' => 8,
            ],
            [
                'key' => 'products_sort_price_desc',
                'value' => 'Giá cao đến thấp',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Sort - Giá giảm dần',
                'description' => 'Tùy chọn sắp xếp giá giảm',
                'order' => 9,
            ],
            [
                'key' => 'products_sort_popular',
                'value' => 'Phổ biến nhất',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Sort - Phổ biến',
                'description' => 'Tùy chọn sắp xếp phổ biến',
                'order' => 10,
            ],
            [
                'key' => 'product_detail_add_to_cart',
                'value' => 'Thêm vào giỏ hàng',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Chi tiết SP - Nút thêm giỏ',
                'description' => 'Text nút thêm vào giỏ hàng',
                'order' => 11,
            ],
            [
                'key' => 'product_detail_description',
                'value' => 'Mô tả sản phẩm',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Chi tiết SP - Tab mô tả',
                'description' => 'Tiêu đề tab mô tả',
                'order' => 12,
            ],
            [
                'key' => 'product_detail_policy_title',
                'value' => 'Chính Sách Đổi Trả',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Chính sách - Tiêu đề',
                'description' => 'Tiêu đề chính sách đổi trả',
                'order' => 13,
            ],
            [
                'key' => 'product_detail_policy_1',
                'value' => 'Đổi trả trong vòng 24 giờ nếu hoa không tươi',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Chính sách - Điều 1',
                'description' => 'Điều khoản đổi trả 1',
                'order' => 14,
            ],
            [
                'key' => 'product_detail_policy_2',
                'value' => 'Hoàn tiền 100% nếu giao hàng quá 2 giờ',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Chính sách - Điều 2',
                'description' => 'Điều khoản đổi trả 2',
                'order' => 15,
            ],
            [
                'key' => 'product_detail_policy_3',
                'value' => 'Cam kết hoa giống 95% hình ảnh',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Chính sách - Điều 3',
                'description' => 'Điều khoản đổi trả 3',
                'order' => 16,
            ],
            [
                'key' => 'product_detail_related_title',
                'value' => 'Sản Phẩm Liên Quan',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Sản phẩm liên quan - Tiêu đề',
                'description' => 'Tiêu đề section sản phẩm liên quan',
                'order' => 17,
            ],
            [
                'key' => 'product_detail_quantity',
                'value' => 'Số lượng',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Chi tiết SP - Số lượng',
                'description' => 'Label số lượng',
                'order' => 18,
            ],
            [
                'key' => 'product_detail_sku',
                'value' => 'Mã SP',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Chi tiết SP - SKU',
                'description' => 'Label mã sản phẩm',
                'order' => 19,
            ],
            [
                'key' => 'product_detail_category',
                'value' => 'Danh mục',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Chi tiết SP - Danh mục',
                'description' => 'Label danh mục',
                'order' => 20,
            ],
            [
                'key' => 'product_detail_stock_available',
                'value' => 'Còn hàng',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Trạng thái - Còn hàng',
                'description' => 'Text còn hàng',
                'order' => 21,
            ],
            [
                'key' => 'product_detail_stock_out',
                'value' => 'Hết hàng',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Trạng thái - Hết hàng',
                'description' => 'Text hết hàng',
                'order' => 22,
            ],
            [
                'key' => 'category_page_breadcrumb_home',
                'value' => 'Trang chủ',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Breadcrumb - Trang chủ',
                'description' => 'Text breadcrumb trang chủ',
                'order' => 23,
            ],
            [
                'key' => 'category_page_products_count',
                'value' => 'sản phẩm',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Số lượng - Đơn vị',
                'description' => 'Đơn vị đếm sản phẩm',
                'order' => 24,
            ],
            [
                'key' => 'category_page_no_products',
                'value' => 'Không có sản phẩm nào trong danh mục này',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Thông báo - Không có SP',
                'description' => 'Thông báo khi danh mục trống',
                'order' => 25,
            ],
            [
                'key' => 'product_card_view_detail',
                'value' => 'Xem chi tiết',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Card SP - Xem chi tiết',
                'description' => 'Text nút xem chi tiết trên card',
                'order' => 26,
            ],
            [
                'key' => 'product_card_quick_add',
                'value' => 'Thêm nhanh',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Card SP - Thêm nhanh',
                'description' => 'Text nút thêm nhanh',
                'order' => 27,
            ],
            [
                'key' => 'product_card_new_badge',
                'value' => 'Mới',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Card SP - Badge mới',
                'description' => 'Text badge sản phẩm mới',
                'order' => 28,
            ],
            [
                'key' => 'product_card_sale_badge',
                'value' => 'Giảm giá',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Card SP - Badge giảm giá',
                'description' => 'Text badge giảm giá',
                'order' => 29,
            ],
            [
                'key' => 'product_card_out_of_stock',
                'value' => 'Hết hàng',
                'type' => 'text',
                'group' => 'product_pages',
                'label' => 'Card SP - Hết hàng',
                'description' => 'Text badge hết hàng',
                'order' => 30,
            ],

            // =========================================
            // GROUP 4: CART & CHECKOUT (35 blocks)
            // =========================================
            [
                'key' => 'cart_page_title',
                'value' => 'Giỏ Hàng Của Bạn',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Tiêu đề',
                'description' => 'Tiêu đề trang giỏ hàng',
                'order' => 1,
            ],
            [
                'key' => 'cart_empty_message',
                'value' => 'Giỏ hàng của bạn đang trống',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Thông báo trống',
                'description' => 'Thông báo khi giỏ hàng trống',
                'order' => 2,
            ],
            [
                'key' => 'cart_continue_shopping',
                'value' => 'Tiếp tục mua sắm',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Tiếp tục mua',
                'description' => 'Text nút tiếp tục mua sắm',
                'order' => 3,
            ],
            [
                'key' => 'cart_product_column',
                'value' => 'Sản phẩm',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Cột sản phẩm',
                'description' => 'Tiêu đề cột sản phẩm',
                'order' => 4,
            ],
            [
                'key' => 'cart_price_column',
                'value' => 'Đơn giá',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Cột giá',
                'description' => 'Tiêu đề cột giá',
                'order' => 5,
            ],
            [
                'key' => 'cart_quantity_column',
                'value' => 'Số lượng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Cột số lượng',
                'description' => 'Tiêu đề cột số lượng',
                'order' => 6,
            ],
            [
                'key' => 'cart_total_column',
                'value' => 'Thành tiền',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Cột tổng',
                'description' => 'Tiêu đề cột thành tiền',
                'order' => 7,
            ],
            [
                'key' => 'cart_remove_item',
                'value' => 'Xóa',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Xóa SP',
                'description' => 'Text nút xóa sản phẩm',
                'order' => 8,
            ],
            [
                'key' => 'cart_update_cart',
                'value' => 'Cập nhật giỏ hàng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Cập nhật',
                'description' => 'Text nút cập nhật giỏ hàng',
                'order' => 9,
            ],
            [
                'key' => 'cart_subtotal',
                'value' => 'Tạm tính',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Tạm tính',
                'description' => 'Label tạm tính',
                'order' => 10,
            ],
            [
                'key' => 'cart_shipping',
                'value' => 'Phí vận chuyển',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Phí ship',
                'description' => 'Label phí vận chuyển',
                'order' => 11,
            ],
            [
                'key' => 'cart_total',
                'value' => 'Tổng cộng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Tổng',
                'description' => 'Label tổng cộng',
                'order' => 12,
            ],
            [
                'key' => 'cart_proceed_checkout',
                'value' => 'Tiến hành thanh toán',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Giỏ hàng - Thanh toán',
                'description' => 'Text nút tiến hành thanh toán',
                'order' => 13,
            ],
            [
                'key' => 'checkout_page_title',
                'value' => 'Thanh Toán',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - Tiêu đề',
                'description' => 'Tiêu đề trang thanh toán',
                'order' => 14,
            ],
            [
                'key' => 'checkout_billing_info',
                'value' => 'Thông tin thanh toán',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - Thông tin TT',
                'description' => 'Tiêu đề section thông tin thanh toán',
                'order' => 15,
            ],
            [
                'key' => 'checkout_full_name',
                'value' => 'Họ và tên',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - Họ tên',
                'description' => 'Label họ và tên',
                'order' => 16,
            ],
            [
                'key' => 'checkout_phone',
                'value' => 'Số điện thoại',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - SĐT',
                'description' => 'Label số điện thoại',
                'order' => 17,
            ],
            [
                'key' => 'checkout_email',
                'value' => 'Email',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - Email',
                'description' => 'Label email',
                'order' => 18,
            ],
            [
                'key' => 'checkout_address',
                'value' => 'Địa chỉ giao hàng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - Địa chỉ',
                'description' => 'Label địa chỉ giao hàng',
                'order' => 19,
            ],
            [
                'key' => 'checkout_note',
                'value' => 'Ghi chú đơn hàng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - Ghi chú',
                'description' => 'Label ghi chú đơn hàng',
                'order' => 20,
            ],
            [
                'key' => 'checkout_payment_method',
                'value' => 'Phương thức thanh toán',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - PTTT',
                'description' => 'Label phương thức thanh toán',
                'order' => 21,
            ],
            [
                'key' => 'checkout_payment_cod',
                'value' => 'Thanh toán khi nhận hàng (COD)',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - COD',
                'description' => 'Text phương thức COD',
                'order' => 22,
            ],
            [
                'key' => 'checkout_payment_bank',
                'value' => 'Chuyển khoản ngân hàng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - Chuyển khoản',
                'description' => 'Text phương thức chuyển khoản',
                'order' => 23,
            ],
            [
                'key' => 'checkout_order_summary',
                'value' => 'Tóm tắt đơn hàng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - Tóm tắt ĐH',
                'description' => 'Tiêu đề tóm tắt đơn hàng',
                'order' => 24,
            ],
            [
                'key' => 'checkout_place_order',
                'value' => 'Đặt hàng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Checkout - Nút đặt hàng',
                'description' => 'Text nút đặt hàng',
                'order' => 25,
            ],
            [
                'key' => 'checkout_success_title',
                'value' => 'Đặt Hàng Thành Công!',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Success - Tiêu đề',
                'description' => 'Tiêu đề trang thành công',
                'order' => 26,
            ],
            [
                'key' => 'checkout_success_message',
                'value' => 'Cảm ơn bạn đã đặt hàng. Chúng tôi sẽ liên hệ với bạn sớm nhất.',
                'type' => 'textarea',
                'group' => 'cart_checkout',
                'label' => 'Success - Thông báo',
                'description' => 'Thông báo đặt hàng thành công',
                'order' => 27,
            ],
            [
                'key' => 'checkout_success_order_number',
                'value' => 'Mã đơn hàng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Success - Mã ĐH',
                'description' => 'Label mã đơn hàng',
                'order' => 28,
            ],
            [
                'key' => 'checkout_success_order_date',
                'value' => 'Ngày đặt hàng',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Success - Ngày đặt',
                'description' => 'Label ngày đặt hàng',
                'order' => 29,
            ],
            [
                'key' => 'checkout_success_order_total',
                'value' => 'Tổng tiền',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Success - Tổng tiền',
                'description' => 'Label tổng tiền',
                'order' => 30,
            ],
            [
                'key' => 'checkout_success_view_orders',
                'value' => 'Xem đơn hàng của tôi',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Success - Xem ĐH',
                'description' => 'Text nút xem đơn hàng',
                'order' => 31,
            ],
            [
                'key' => 'checkout_success_continue_shopping',
                'value' => 'Tiếp tục mua sắm',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Success - Tiếp tục',
                'description' => 'Text nút tiếp tục mua sắm',
                'order' => 32,
            ],
            [
                'key' => 'checkout_shipping_free',
                'value' => 'Miễn phí',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Shipping - Miễn phí',
                'description' => 'Text phí ship miễn phí',
                'order' => 33,
            ],
            [
                'key' => 'checkout_apply_coupon',
                'value' => 'Áp dụng mã giảm giá',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Coupon - Áp dụng',
                'description' => 'Text áp dụng mã giảm giá',
                'order' => 34,
            ],
            [
                'key' => 'checkout_coupon_code',
                'value' => 'Mã giảm giá',
                'type' => 'text',
                'group' => 'cart_checkout',
                'label' => 'Coupon - Mã',
                'description' => 'Label mã giảm giá',
                'order' => 35,
            ],

            // =========================================
            // GROUP 5: BLOG & PAGES (8 blocks)
            // =========================================
            [
                'key' => 'blog_page_title',
                'value' => 'Blog & Tin Tức',
                'type' => 'text',
                'group' => 'blog_pages',
                'label' => 'Blog - Tiêu đề',
                'description' => 'Tiêu đề trang blog',
                'order' => 1,
            ],
            [
                'key' => 'blog_read_more',
                'value' => 'Đọc thêm',
                'type' => 'text',
                'group' => 'blog_pages',
                'label' => 'Blog - Đọc thêm',
                'description' => 'Text nút đọc thêm',
                'order' => 2,
            ],
            [
                'key' => 'blog_recent_posts',
                'value' => 'Bài viết mới nhất',
                'type' => 'text',
                'group' => 'blog_pages',
                'label' => 'Blog - Bài mới',
                'description' => 'Tiêu đề bài viết mới nhất',
                'order' => 3,
            ],
            [
                'key' => 'blog_categories',
                'value' => 'Danh mục',
                'type' => 'text',
                'group' => 'blog_pages',
                'label' => 'Blog - Danh mục',
                'description' => 'Tiêu đề danh mục blog',
                'order' => 4,
            ],
            [
                'key' => 'blog_search_placeholder',
                'value' => 'Tìm kiếm bài viết...',
                'type' => 'text',
                'group' => 'blog_pages',
                'label' => 'Blog - Search',
                'description' => 'Placeholder tìm kiếm blog',
                'order' => 5,
            ],
            [
                'key' => 'contact_page_title',
                'value' => 'Liên Hệ Với Chúng Tôi',
                'type' => 'text',
                'group' => 'blog_pages',
                'label' => 'Contact - Tiêu đề',
                'description' => 'Tiêu đề trang liên hệ',
                'order' => 6,
            ],
            [
                'key' => 'contact_send_message',
                'value' => 'Gửi tin nhắn',
                'type' => 'text',
                'group' => 'blog_pages',
                'label' => 'Contact - Nút gửi',
                'description' => 'Text nút gửi tin nhắn',
                'order' => 7,
            ],
            [
                'key' => 'about_page_title',
                'value' => 'Về Chúng Tôi',
                'type' => 'text',
                'group' => 'blog_pages',
                'label' => 'About - Tiêu đề',
                'description' => 'Tiêu đề trang giới thiệu',
                'order' => 8,
            ],

            // =========================================
            // GROUP 6: COMPONENTS (15 blocks)
            // =========================================
            [
                'key' => 'promotion_bar_text',
                'value' => 'Miễn phí giao hàng cho đơn từ 500.000đ - Gọi ngay: 1900 1234',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Promotion Bar - Text',
                'description' => 'Nội dung thanh khuyến mãi',
                'order' => 1,
            ],
            [
                'key' => 'zalo_info_title',
                'value' => 'Đặt Hoa Qua Zalo',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Zalo - Tiêu đề',
                'description' => 'Tiêu đề popup Zalo',
                'order' => 2,
            ],
            [
                'key' => 'zalo_benefit_1',
                'value' => 'Tư vấn miễn phí 24/7',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Zalo - Lợi ích 1',
                'description' => 'Lợi ích đặt hàng qua Zalo 1',
                'order' => 3,
            ],
            [
                'key' => 'zalo_benefit_2',
                'value' => 'Xem hình thật trước khi giao',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Zalo - Lợi ích 2',
                'description' => 'Lợi ích đặt hàng qua Zalo 2',
                'order' => 4,
            ],
            [
                'key' => 'zalo_benefit_3',
                'value' => 'Giảm ngay 50k cho đơn đầu',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Zalo - Lợi ích 3',
                'description' => 'Lợi ích đặt hàng qua Zalo 3',
                'order' => 5,
            ],
            [
                'key' => 'zalo_cta',
                'value' => 'Chat Zalo ngay',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Zalo - CTA',
                'description' => 'Text nút chat Zalo',
                'order' => 6,
            ],
            [
                'key' => 'zalo_faq_title',
                'value' => 'Câu hỏi thường gặp',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Zalo FAQ - Tiêu đề',
                'description' => 'Tiêu đề phần FAQ trong Zalo popup',
                'order' => 7,
            ],
            [
                'key' => 'zalo_faq_1_question',
                'value' => 'Làm sao để đặt hoa qua Zalo?',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Zalo FAQ 1 - Câu hỏi',
                'description' => 'Câu hỏi FAQ 1',
                'order' => 8,
            ],
            [
                'key' => 'zalo_faq_1_answer',
                'value' => 'Bạn chỉ cần nhắn tin qua Zalo, gửi ảnh mẫu hoặc mô tả yêu cầu. Chúng tôi sẽ tư vấn và báo giá ngay.',
                'type' => 'textarea',
                'group' => 'components',
                'label' => 'Zalo FAQ 1 - Trả lời',
                'description' => 'Câu trả lời FAQ 1',
                'order' => 9,
            ],
            [
                'key' => 'zalo_faq_2_question',
                'value' => 'Có được xem hoa trước khi giao không?',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Zalo FAQ 2 - Câu hỏi',
                'description' => 'Câu hỏi FAQ 2',
                'order' => 10,
            ],
            [
                'key' => 'zalo_faq_2_answer',
                'value' => 'Có, chúng tôi sẽ chụp hình thực tế và gửi cho bạn xác nhận qua Zalo trước khi giao.',
                'type' => 'textarea',
                'group' => 'components',
                'label' => 'Zalo FAQ 2 - Trả lời',
                'description' => 'Câu trả lời FAQ 2',
                'order' => 11,
            ],
            [
                'key' => 'product_card_add_to_cart',
                'value' => 'Thêm vào giỏ',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Product Card - Add to cart',
                'description' => 'Text nút thêm vào giỏ trên card',
                'order' => 12,
            ],
            [
                'key' => 'product_card_sold_out',
                'value' => 'Đã hết hàng',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Product Card - Sold out',
                'description' => 'Text trạng thái hết hàng',
                'order' => 13,
            ],
            [
                'key' => 'newsletter_title',
                'value' => 'Đăng Ký Nhận Tin',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Newsletter - Tiêu đề',
                'description' => 'Tiêu đề form đăng ký nhận tin',
                'order' => 14,
            ],
            [
                'key' => 'newsletter_placeholder',
                'value' => 'Nhập email của bạn',
                'type' => 'text',
                'group' => 'components',
                'label' => 'Newsletter - Placeholder',
                'description' => 'Placeholder input email',
                'order' => 15,
            ],

            // =========================================
            // GROUP 7: LAYOUT (13 blocks)
            // =========================================
            [
                'key' => 'chat_widget_greeting',
                'value' => 'Xin chào! Chúng tôi có thể giúp gì cho bạn?',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Chat - Lời chào',
                'description' => 'Lời chào chat widget',
                'order' => 1,
            ],
            [
                'key' => 'chat_widget_placeholder',
                'value' => 'Nhập tin nhắn...',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Chat - Placeholder',
                'description' => 'Placeholder input chat',
                'order' => 2,
            ],
            [
                'key' => 'chat_widget_send',
                'value' => 'Gửi',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Chat - Nút gửi',
                'description' => 'Text nút gửi chat',
                'order' => 3,
            ],
            [
                'key' => 'chat_widget_online',
                'value' => 'Đang online',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Chat - Trạng thái online',
                'description' => 'Text trạng thái online',
                'order' => 4,
            ],
            [
                'key' => 'chat_widget_offline',
                'value' => 'Đang offline',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Chat - Trạng thái offline',
                'description' => 'Text trạng thái offline',
                'order' => 5,
            ],
            [
                'key' => 'chat_widget_response_time',
                'value' => 'Thường phản hồi trong vài phút',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Chat - Thời gian phản hồi',
                'description' => 'Text thời gian phản hồi',
                'order' => 6,
            ],
            [
                'key' => 'footer_about_us',
                'value' => 'Về chúng tôi',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Footer - Về chúng tôi',
                'description' => 'Tiêu đề cột về chúng tôi',
                'order' => 7,
            ],
            [
                'key' => 'footer_customer_service',
                'value' => 'Chăm sóc khách hàng',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Footer - CSKH',
                'description' => 'Tiêu đề cột chăm sóc khách hàng',
                'order' => 8,
            ],
            [
                'key' => 'footer_follow_us',
                'value' => 'Theo dõi chúng tôi',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Footer - Follow',
                'description' => 'Tiêu đề cột mạng xã hội',
                'order' => 9,
            ],
            [
                'key' => 'footer_copyright',
                'value' => '© 2026 FlowerShop. All rights reserved.',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Footer - Copyright',
                'description' => 'Text bản quyền',
                'order' => 10,
            ],
            [
                'key' => 'navbar_search_placeholder',
                'value' => 'Tìm kiếm sản phẩm...',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Navbar - Search',
                'description' => 'Placeholder tìm kiếm navbar',
                'order' => 11,
            ],
            [
                'key' => 'navbar_cart_empty',
                'value' => 'Giỏ hàng trống',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Navbar - Giỏ trống',
                'description' => 'Text giỏ hàng trống',
                'order' => 12,
            ],
            [
                'key' => 'navbar_view_cart',
                'value' => 'Xem giỏ hàng',
                'type' => 'text',
                'group' => 'layout',
                'label' => 'Navbar - Xem giỏ',
                'description' => 'Text nút xem giỏ hàng',
                'order' => 13,
            ],

            // =========================================
            // GROUP 8: AUTH (40 blocks)
            // =========================================
            [
                'key' => 'login_page_title',
                'value' => 'Đăng Nhập',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Tiêu đề',
                'description' => 'Tiêu đề trang đăng nhập',
                'order' => 1,
            ],
            [
                'key' => 'login_welcome',
                'value' => 'Chào mừng trở lại!',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Welcome',
                'description' => 'Lời chào trang đăng nhập',
                'order' => 2,
            ],
            [
                'key' => 'login_subtitle',
                'value' => 'Đăng nhập để tiếp tục mua sắm',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Subtitle',
                'description' => 'Phụ đề trang đăng nhập',
                'order' => 3,
            ],
            [
                'key' => 'login_email_label',
                'value' => 'Email',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Email label',
                'description' => 'Label email đăng nhập',
                'order' => 4,
            ],
            [
                'key' => 'login_email_placeholder',
                'value' => 'Nhập email của bạn',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Email placeholder',
                'description' => 'Placeholder email đăng nhập',
                'order' => 5,
            ],
            [
                'key' => 'login_password_label',
                'value' => 'Mật khẩu',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Password label',
                'description' => 'Label mật khẩu đăng nhập',
                'order' => 6,
            ],
            [
                'key' => 'login_password_placeholder',
                'value' => 'Nhập mật khẩu',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Password placeholder',
                'description' => 'Placeholder mật khẩu đăng nhập',
                'order' => 7,
            ],
            [
                'key' => 'login_remember_me',
                'value' => 'Ghi nhớ đăng nhập',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Remember me',
                'description' => 'Text checkbox ghi nhớ',
                'order' => 8,
            ],
            [
                'key' => 'login_forgot_password',
                'value' => 'Quên mật khẩu?',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Forgot password',
                'description' => 'Text link quên mật khẩu',
                'order' => 9,
            ],
            [
                'key' => 'login_submit_button',
                'value' => 'Đăng nhập',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Submit button',
                'description' => 'Text nút đăng nhập',
                'order' => 10,
            ],
            [
                'key' => 'login_no_account',
                'value' => 'Chưa có tài khoản?',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - No account',
                'description' => 'Text chưa có tài khoản',
                'order' => 11,
            ],
            [
                'key' => 'login_register_link',
                'value' => 'Đăng ký ngay',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Register link',
                'description' => 'Text link đăng ký',
                'order' => 12,
            ],
            [
                'key' => 'login_or_divider',
                'value' => 'Hoặc đăng nhập với',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Or divider',
                'description' => 'Text phân cách đăng nhập social',
                'order' => 13,
            ],
            [
                'key' => 'login_google',
                'value' => 'Google',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Google',
                'description' => 'Text nút đăng nhập Google',
                'order' => 14,
            ],
            [
                'key' => 'login_facebook',
                'value' => 'Facebook',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Facebook',
                'description' => 'Text nút đăng nhập Facebook',
                'order' => 15,
            ],
            [
                'key' => 'login_brand_tagline',
                'value' => 'Hoa tươi mỗi ngày, yêu thương mỗi giây',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Brand tagline',
                'description' => 'Tagline thương hiệu trang login',
                'order' => 16,
            ],
            [
                'key' => 'login_brand_description',
                'value' => 'Mang đến những bó hoa tươi đẹp nhất cho người thân yêu của bạn',
                'type' => 'textarea',
                'group' => 'auth',
                'label' => 'Login - Brand description',
                'description' => 'Mô tả thương hiệu trang login',
                'order' => 17,
            ],
            [
                'key' => 'login_benefit_1',
                'value' => 'Giao hàng nhanh trong 2 giờ',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Benefit 1',
                'description' => 'Lợi ích 1',
                'order' => 18,
            ],
            [
                'key' => 'login_benefit_2',
                'value' => 'Hoa tươi 100% cam kết',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Benefit 2',
                'description' => 'Lợi ích 2',
                'order' => 19,
            ],
            [
                'key' => 'login_benefit_3',
                'value' => 'Thiết kế bởi florist chuyên nghiệp',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Login - Benefit 3',
                'description' => 'Lợi ích 3',
                'order' => 20,
            ],
            [
                'key' => 'register_page_title',
                'value' => 'Đăng Ký',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Tiêu đề',
                'description' => 'Tiêu đề trang đăng ký',
                'order' => 21,
            ],
            [
                'key' => 'register_welcome',
                'value' => 'Tạo tài khoản mới',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Welcome',
                'description' => 'Lời chào trang đăng ký',
                'order' => 22,
            ],
            [
                'key' => 'register_subtitle',
                'value' => 'Đăng ký để nhận ưu đãi đặc biệt',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Subtitle',
                'description' => 'Phụ đề trang đăng ký',
                'order' => 23,
            ],
            [
                'key' => 'register_fullname_label',
                'value' => 'Họ và tên',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Fullname label',
                'description' => 'Label họ tên đăng ký',
                'order' => 24,
            ],
            [
                'key' => 'register_fullname_placeholder',
                'value' => 'Nhập họ và tên',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Fullname placeholder',
                'description' => 'Placeholder họ tên đăng ký',
                'order' => 25,
            ],
            [
                'key' => 'register_email_label',
                'value' => 'Email',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Email label',
                'description' => 'Label email đăng ký',
                'order' => 26,
            ],
            [
                'key' => 'register_email_placeholder',
                'value' => 'Nhập email của bạn',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Email placeholder',
                'description' => 'Placeholder email đăng ký',
                'order' => 27,
            ],
            [
                'key' => 'register_phone_label',
                'value' => 'Số điện thoại',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Phone label',
                'description' => 'Label số điện thoại đăng ký',
                'order' => 28,
            ],
            [
                'key' => 'register_phone_placeholder',
                'value' => 'Nhập số điện thoại',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Phone placeholder',
                'description' => 'Placeholder số điện thoại đăng ký',
                'order' => 29,
            ],
            [
                'key' => 'register_password_label',
                'value' => 'Mật khẩu',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Password label',
                'description' => 'Label mật khẩu đăng ký',
                'order' => 30,
            ],
            [
                'key' => 'register_password_placeholder',
                'value' => 'Nhập mật khẩu',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Password placeholder',
                'description' => 'Placeholder mật khẩu đăng ký',
                'order' => 31,
            ],
            [
                'key' => 'register_confirm_password_label',
                'value' => 'Xác nhận mật khẩu',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Confirm password label',
                'description' => 'Label xác nhận mật khẩu',
                'order' => 32,
            ],
            [
                'key' => 'register_confirm_password_placeholder',
                'value' => 'Nhập lại mật khẩu',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Confirm password placeholder',
                'description' => 'Placeholder xác nhận mật khẩu',
                'order' => 33,
            ],
            [
                'key' => 'register_terms_prefix',
                'value' => 'Tôi đồng ý với',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Terms prefix',
                'description' => 'Text trước link điều khoản',
                'order' => 34,
            ],
            [
                'key' => 'register_terms_link',
                'value' => 'Điều khoản sử dụng',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Terms link',
                'description' => 'Text link điều khoản',
                'order' => 35,
            ],
            [
                'key' => 'register_submit_button',
                'value' => 'Đăng ký',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Submit button',
                'description' => 'Text nút đăng ký',
                'order' => 36,
            ],
            [
                'key' => 'register_have_account',
                'value' => 'Đã có tài khoản?',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Have account',
                'description' => 'Text đã có tài khoản',
                'order' => 37,
            ],
            [
                'key' => 'register_login_link',
                'value' => 'Đăng nhập ngay',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Login link',
                'description' => 'Text link đăng nhập',
                'order' => 38,
            ],
            [
                'key' => 'register_brand_tagline',
                'value' => 'Tham gia cộng đồng yêu hoa',
                'type' => 'text',
                'group' => 'auth',
                'label' => 'Register - Brand tagline',
                'description' => 'Tagline thương hiệu trang register',
                'order' => 39,
            ],
            [
                'key' => 'register_brand_description',
                'value' => 'Đăng ký ngay để nhận ưu đãi 50k cho đơn hàng đầu tiên',
                'type' => 'textarea',
                'group' => 'auth',
                'label' => 'Register - Brand description',
                'description' => 'Mô tả thương hiệu trang register',
                'order' => 40,
            ],

            // =========================================
            // GROUP 9: ADMIN (3 blocks)
            // =========================================
            [
                'key' => 'admin_dashboard_subtitle',
                'value' => 'Tổng quan hệ thống',
                'type' => 'text',
                'group' => 'admin',
                'label' => 'Dashboard - Subtitle',
                'description' => 'Phụ đề trang dashboard',
                'order' => 1,
            ],
            [
                'key' => 'admin_welcome_message',
                'value' => 'Chào mừng bạn quay trở lại!',
                'type' => 'text',
                'group' => 'admin',
                'label' => 'Dashboard - Welcome',
                'description' => 'Lời chào dashboard',
                'order' => 2,
            ],
            [
                'key' => 'admin_quick_stats_title',
                'value' => 'Thống Kê Nhanh',
                'type' => 'text',
                'group' => 'admin',
                'label' => 'Dashboard - Quick stats',
                'description' => 'Tiêu đề thống kê nhanh',
                'order' => 3,
            ],
        ];

        // Insert all blocks
        foreach ($blocks as $block) {
            ContentBlock::updateOrCreate(
                ['key' => $block['key']],
                $block
            );
        }

        $this->command->info('✅ Đã seed ' . count($blocks) . ' content blocks thành công!');
    }
}
